name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: dev # Replace with the label of your self-hosted runner

    strategy:
      matrix:
        node-version: [14] # Use the specific Node.js version you need

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build and Test
      run: |
        npm run build
        npm test

    - name: Start the Node.js application
      run: |
        nohup npm start &
